# Generated by Django 3.2.19 on 2023-07-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('ebay', models.CharField(max_length=30)),
                ('subito', models.CharField(max_length=30)),
                ('vinted', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
