# Generated by Django 3.2.19 on 2023-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ebay',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subito',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='vinted',
            field=models.CharField(max_length=50),
        ),
    ]
